[28기 강민성] Add: Products 상품 전체 리스트, 상세 페이지 구현
wecode-bootcamp-korea/28-1st-Gamsung-backend pull request #5
Opened 2022-01-04 03:14 UTC by nonasking

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- Products app을 통해 상품 전체 리스트 페이지와 상품 상세 페이지 라우팅, 뷰 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. gamsung/urls.py에 products의 url 추가
2. products/views.py에 상품 전체 리스트 뷰(ListView), 디테일 페이지 뷰(DetailView)작성
3. products/urls.py에 상품 전체 리스트와 디테일 페이지 라우팅
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-01-04 05:06 UTC, kyeongraekim requested changes
아래 내용 확인 후 수정해주세요!~

2022-01-04 05:06 UTC, kyeongraekim commented on products/views.py
> +            products_list.append({'name':product.name, 'subcategory':subcategory.name, 'serial_number':product.serial_number, 'storage':storage.storage, 'price':product.price, 'main_image':main_image
빈리스트 선언 및 append로 데이터 붙이는 것에 성공하셨으니,
해당 내용 리스트 컴프리헨션을 적용하여서 보다 효율적인 코드로의 진행에 한 번 도전해보세요!
그리고 가독성을 위해서 아래와 같은 형태로 데이터 변수를 지정해주세요!~

```python

{
    'name'        : product.name
    'subcategory' : subcategory.name 
}

2022-01-04 05:06 UTC, kyeongraekim commented on products/views.py
> +        product_details_list.append({'name':product.name, 'serial_number':product.serial_number, 'storage':storage.storage, 'price':product.price, 'main_image':main_image, 'detail_images':detail_imag
이곳도 리뷰내용, 위 리뷰와 동일합니다!~

2022-01-04 11:19 UTC, nonasking commented on products/views.py
> +        product_details_list.append({'name':product.name, 'serial_number':product.serial_number, 'storage':storage.storage, 'price':product.price, 'main_image':main_image, 'detail_images':detail_imag
리뷰 반영 + 기능 추가(filtering, pagination)하여 push했습니다. 검토 부탁드립니다 :)
(PR 템플릿에 질문 올렸습니다!)

2022-01-05 01:28 UTC, kyeongraekim requested changes
아래 내용 확인하여 수정해주세요!~

2022-01-05 01:28 UTC, kyeongraekim commented on products/views.py
> +        limit           = offset + int(request.GET.get('limit', 10))
limit값은 그대로 받아주시고 아래에서 [offset: limit+offset] 으로 인덱싱을 해주시면 확장성 고려 더 올바른 코딩이 될 것 같네요!~

2022-01-05 01:28 UTC, kyeongraekim commented on products/views.py
> +                'storage'      : ProductStorage.objects.get(product=product).storage.storage,
뒤에 storage.storage로 끝나는 내용이 뭔가 의미적으로 명확해보이지는 않아보이네요~ 해당내용의 가독성과 의미성을 확실히 잡기 위해서 어떤 부분을 어떻게 변경해볼 수 있을까요?

2022-01-06 02:37 UTC, kyeongraekim requested changes
민성님 마이너한 수정 소요 반영해드립니다!~

2022-01-06 02:37 UTC, kyeongraekim commented on products/views.py
> +            print(search_content)
디버깅용 프린트 문이 아직 남아있네요!~  Push 전에 git diff 찍어보셔서 꼭 전체 파일 확인해주시는 습관 들여주세요~ ㅎㅎ

2022-01-06 02:41 UTC, nonasking commented on products/views.py
> +            print(search_content)
앗 실수했네요! 수정해서 다시 푸시했습니다

2022-01-06 05:33 UTC, kyeongraekim approved these changes
LGTM!~

2022-01-06 05:33 UTC, merged